### ISSUE TITLE
The version after 1.1.106 will be abnormal when playing pokemon arzeus, and the version 1.1.106 is normal

### ISSUE THREAD

**Issue by adrianwlf** [Ryujinx/release-channel-master#2]
The version after 1.1.106 will be abnormal when playing pokemon arzeus, and the version 1.1.106 is normal

**Comment by gdkchan** [comment]
Issues should be opened on the main repository, not here. There's already one for this problem: https://github.com/Ryujinx/Ryujinx/issues/3309
