### ISSUE TITLE
1.1.220 runs horribly

### ISSUE THREAD

**Issue by Missingphy** [Ryujinx/release-channel-master#3]
Hello, so this is a great emulator, I've been using it instead of Yuzu because it has proper Vsync support which lets me play without tearing/no fps drop stuttering, I stopped playing my games for a while (mk8dx and smo) so I left ryujinx on version 209. Today I updated 
to 220 and the game runs well for some periods, but lags horribly after other some, but it's not fps drops, my shadowplay shows solid 60fps yet it still lags. I downgraded to 209 and the emulator works as I left it when I last played, I tried several versions, and 217 is the latest one which lets me play without lag. My graphics settings (209, 217 and 220 are all the same settings but 220 lags) 
![thxtttt](https://user-images.githubusercontent.com/49085233/185262613-71f0719c-0200-41d9-9d00-61ab96e32fa5.png)

Otherwise great emulator, 9/10, would recommend to others.

**Comment by AcK77** [comment]
This is not the place for that. Please open an issue on our main repo on go to our discord for support. Thanks.
